language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: NKGxKjvFivHWdi/lAVmpOU+WcpLocemfIBD9jieBVI+++v50p6fVy7k8/lMEs8BSWSvZkKqYWwVzD7L+3RsUjM56amxRGyz1FtSdvRkstenkggFhxMN3fFUYuqjOn8WqIUiByf8mhmzjnLtolc86MjgKXjV42iDjSxZ804hoHsNcZzN1xnqKsEibcfHc6EXwcWwHYxgLy7nRH9us9MCFYY/UycpfL1V072ZabxK9ZwAzwJusn1ofH8qllsKWm/TY/2KeMINL5p8LeBNnJdpKdeOIi58qWrphHp5bma0xDN+8Ff5tkcg6VWCaYYhqiYB7j7L1nVVxhUseSNk29teGhXEazmEQwTlIvLScBIoLQ9P4b5958WVtDoxdd7lCn4sNZ2J8CzjGO0N/Ow+m4n1BN2J2ZUTcViiXyaGN1EWh8EuDQSXTmuOZLs0gicVsfa12oczNTi1HpyOSx6ZzdYmx84OooQ5x/yjLytJWDCLJNo7Ir3iOJG7EcT2VAMrPZwB5gwdro6/R4XJAXuzdsmRdu6i0Jlb3PKmQoLfBaU6UKzXc/rHyHGfJqImNFcD0pJbajb5hkHy44HJRjEQGt4LmW2dJnKLifqhOa9O4ue9CAl261dj+uhowpObiOr4h7ngRDFJ4Lw88qpt18rdZ7l9QEn0d/KvnxCUhRzW9hh0l8a4=
  file: xv6.img
  on:
    repo: noespinoza/xv6-public
    branch: project_2
